# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_head_agent
  - /habitat/task/rearrange: nav_to_obj
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  gym:
    obs_keys:
      - head_depth
      - head_rgb
      - goal_to_agent_gps_compass
      - joint
  environment:
    max_episode_steps: 400
  simulator:
    type: RearrangeSim-v0
    additional_object_paths:
      - data/objects/ycb/configs/
    needs_markers: False
    concur_render: True
    auto_sleep: True
    agents:
      main_agent:
        height: 1.5
        is_set_start_state: False
        radius: 0.1
        sim_sensors:
          head_depth_sensor:
            height: 256
            width: 256
          head_rgb_sensor:
            height: 256
            width: 256
        start_position: [0, 0, 0]
        start_rotation: [0, 0, 0, 1]
        articulated_agent_urdf: ./data/robots/hab_fetch/robots/hab_fetch.urdf
        articulated_agent_type: FetchRobot

    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True


  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/ks_rearrange.json.gz
