name: "KSPolicy"
obs_transforms:
  add_virtual_keys:
    virtual_keys:
      "goal_to_agent_gps_compass": 2
action_distribution_type: "gaussian"
action_dist:
  use_log_std: True
hierarchical_policy:
  high_level_policy:
    name: "FixedHighLevelPolicy"
    add_arm_rest: False
  defined_skills: {}