# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: depth_base
  - /habitat/simulator/sim_sensors@habitat.simulator.agents.main_agent.sim_sensors.head_rgb_sensor: head_rgb_sensor
  - /habitat/task/rearrange: rearrange_easy
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  gym:
    obs_keys:
      - head_rgb  ## 256*256*3
      - relative_resting_position ## 3-dim ee to rest_ee position
      - obj_start_sensor    ## start object position 3-dim
      - obj_goal_sensor     ## goal object position 3-dim
      - obj_start_gps_compass ## start object gps 2-dim  in 2D polar coordinates (distance, angle)
      - obj_goal_gps_compass  ## goal object gps 2-dim  in 2D polar coordinates
      - joint           ## 7-dim
      - is_holding      ## 0 or 1 
      - ee_pos          ## end-effector position 3-dim
  environment:
    max_episode_steps: 800
  simulator:
    type: RearrangeSim-v0
    additional_object_paths:
      - "data/objects/ycb/configs/"
    concur_render: True
    auto_sleep: True
    agents:
      main_agent:
        radius: 0.3
        articulated_agent_urdf: ./data/robots/hab_fetch/robots/hab_suction.urdf
        articulated_agent_type: FetchSuctionRobot
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
      
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy_1.json.gz
